//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FenealgestWEB.FenealgestUtilsService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FenealgestUtilsSoap", Namespace="http://www.fenealgestweb.it/")]
    public partial class FenealgestUtils : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CalcolaCodiceFiscaleOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExportDocumentToExcelOperationCompleted;
        
        private System.Threading.SendOrPostCallback CalcolaDatiFiscaliOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExportTessereOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImportDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FenealgestUtils() {
            this.Url = global::FenealgestWEB.Properties.Settings.Default.FenealgestWEB_FenealgestUtilsService_FenealgestUtils;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CalcolaCodiceFiscaleCompletedEventHandler CalcolaCodiceFiscaleCompleted;
        
        /// <remarks/>
        public event ExportDocumentToExcelCompletedEventHandler ExportDocumentToExcelCompleted;
        
        /// <remarks/>
        public event CalcolaDatiFiscaliCompletedEventHandler CalcolaDatiFiscaliCompleted;
        
        /// <remarks/>
        public event ExportTessereCompletedEventHandler ExportTessereCompleted;
        
        /// <remarks/>
        public event ImportDataCompletedEventHandler ImportDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fenealgestweb.it/CalcolaCodiceFiscale", RequestNamespace="http://www.fenealgestweb.it/", ResponseNamespace="http://www.fenealgestweb.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CalcolaCodiceFiscale(string nome, string cognome, System.DateTime dataNascita, string sesso, string nomeComuneNascita, string nomeNazione) {
            object[] results = this.Invoke("CalcolaCodiceFiscale", new object[] {
                        nome,
                        cognome,
                        dataNascita,
                        sesso,
                        nomeComuneNascita,
                        nomeNazione});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CalcolaCodiceFiscaleAsync(string nome, string cognome, System.DateTime dataNascita, string sesso, string nomeComuneNascita, string nomeNazione) {
            this.CalcolaCodiceFiscaleAsync(nome, cognome, dataNascita, sesso, nomeComuneNascita, nomeNazione, null);
        }
        
        /// <remarks/>
        public void CalcolaCodiceFiscaleAsync(string nome, string cognome, System.DateTime dataNascita, string sesso, string nomeComuneNascita, string nomeNazione, object userState) {
            if ((this.CalcolaCodiceFiscaleOperationCompleted == null)) {
                this.CalcolaCodiceFiscaleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalcolaCodiceFiscaleOperationCompleted);
            }
            this.InvokeAsync("CalcolaCodiceFiscale", new object[] {
                        nome,
                        cognome,
                        dataNascita,
                        sesso,
                        nomeComuneNascita,
                        nomeNazione}, this.CalcolaCodiceFiscaleOperationCompleted, userState);
        }
        
        private void OnCalcolaCodiceFiscaleOperationCompleted(object arg) {
            if ((this.CalcolaCodiceFiscaleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalcolaCodiceFiscaleCompleted(this, new CalcolaCodiceFiscaleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fenealgestweb.it/ExportDocumentToExcel", RequestNamespace="http://www.fenealgestweb.it/", ResponseNamespace="http://www.fenealgestweb.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExportDocumentToExcel(ExcelDocument document) {
            object[] results = this.Invoke("ExportDocumentToExcel", new object[] {
                        document});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void ExportDocumentToExcelAsync(ExcelDocument document) {
            this.ExportDocumentToExcelAsync(document, null);
        }
        
        /// <remarks/>
        public void ExportDocumentToExcelAsync(ExcelDocument document, object userState) {
            if ((this.ExportDocumentToExcelOperationCompleted == null)) {
                this.ExportDocumentToExcelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExportDocumentToExcelOperationCompleted);
            }
            this.InvokeAsync("ExportDocumentToExcel", new object[] {
                        document}, this.ExportDocumentToExcelOperationCompleted, userState);
        }
        
        private void OnExportDocumentToExcelOperationCompleted(object arg) {
            if ((this.ExportDocumentToExcelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExportDocumentToExcelCompleted(this, new ExportDocumentToExcelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fenealgestweb.it/CalcolaDatiFiscali", RequestNamespace="http://www.fenealgestweb.it/", ResponseNamespace="http://www.fenealgestweb.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FiscalData CalcolaDatiFiscali(string codiceFiscale) {
            object[] results = this.Invoke("CalcolaDatiFiscali", new object[] {
                        codiceFiscale});
            return ((FiscalData)(results[0]));
        }
        
        /// <remarks/>
        public void CalcolaDatiFiscaliAsync(string codiceFiscale) {
            this.CalcolaDatiFiscaliAsync(codiceFiscale, null);
        }
        
        /// <remarks/>
        public void CalcolaDatiFiscaliAsync(string codiceFiscale, object userState) {
            if ((this.CalcolaDatiFiscaliOperationCompleted == null)) {
                this.CalcolaDatiFiscaliOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalcolaDatiFiscaliOperationCompleted);
            }
            this.InvokeAsync("CalcolaDatiFiscali", new object[] {
                        codiceFiscale}, this.CalcolaDatiFiscaliOperationCompleted, userState);
        }
        
        private void OnCalcolaDatiFiscaliOperationCompleted(object arg) {
            if ((this.CalcolaDatiFiscaliCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalcolaDatiFiscaliCompleted(this, new CalcolaDatiFiscaliCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fenealgestweb.it/ExportTessere", RequestNamespace="http://www.fenealgestweb.it/", ResponseNamespace="http://www.fenealgestweb.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExportTessere(string settore, string provincia, Tesserato[] tesserati) {
            object[] results = this.Invoke("ExportTessere", new object[] {
                        settore,
                        provincia,
                        tesserati});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void ExportTessereAsync(string settore, string provincia, Tesserato[] tesserati) {
            this.ExportTessereAsync(settore, provincia, tesserati, null);
        }
        
        /// <remarks/>
        public void ExportTessereAsync(string settore, string provincia, Tesserato[] tesserati, object userState) {
            if ((this.ExportTessereOperationCompleted == null)) {
                this.ExportTessereOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExportTessereOperationCompleted);
            }
            this.InvokeAsync("ExportTessere", new object[] {
                        settore,
                        provincia,
                        tesserati}, this.ExportTessereOperationCompleted, userState);
        }
        
        private void OnExportTessereOperationCompleted(object arg) {
            if ((this.ExportTessereCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExportTessereCompleted(this, new ExportTessereCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fenealgestweb.it/ImportData", RequestNamespace="http://www.fenealgestweb.it/", ResponseNamespace="http://www.fenealgestweb.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ImportData([System.Xml.Serialization.XmlElementAttribute(Namespace="www.fenealgestweb.it")] ExportTrace ExportTrace) {
            object[] results = this.Invoke("ImportData", new object[] {
                        ExportTrace});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ImportDataAsync(ExportTrace ExportTrace) {
            this.ImportDataAsync(ExportTrace, null);
        }
        
        /// <remarks/>
        public void ImportDataAsync(ExportTrace ExportTrace, object userState) {
            if ((this.ImportDataOperationCompleted == null)) {
                this.ImportDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportDataOperationCompleted);
            }
            this.InvokeAsync("ImportData", new object[] {
                        ExportTrace}, this.ImportDataOperationCompleted, userState);
        }
        
        private void OnImportDataOperationCompleted(object arg) {
            if ((this.ImportDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImportDataCompleted(this, new ImportDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fenealgestweb.it/")]
    public partial class ExcelDocument {
        
        private ExcelRow[] rowsField;
        
        /// <remarks/>
        public ExcelRow[] Rows {
            get {
                return this.rowsField;
            }
            set {
                this.rowsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fenealgestweb.it/")]
    public partial class ExcelRow {
        
        private ExcelProperty[] propertiesField;
        
        private ExcelDocument documentField;
        
        /// <remarks/>
        public ExcelProperty[] Properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
        
        /// <remarks/>
        public ExcelDocument Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fenealgestweb.it/")]
    public partial class ExcelProperty {
        
        private int priorityField;
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public int Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.fenealgestweb.it")]
    public partial class DocumentDTO {
        
        private System.DateTime documentDateField;
        
        private string documentTypeField;
        
        private string strutturaField;
        
        private string areaField;
        
        private string provinceField;
        
        private string cityField;
        
        private string regionField;
        
        private string stateField;
        
        private string notesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DocumentDate {
            get {
                return this.documentDateField;
            }
            set {
                this.documentDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Struttura {
            get {
                return this.strutturaField;
            }
            set {
                this.strutturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.fenealgestweb.it")]
    public partial class SubscriptionDTO {
        
        private string strutturaField;
        
        private string areaField;
        
        private string sectorField;
        
        private string contractField;
        
        private string regionField;
        
        private string entityField;
        
        private string employCompanyField;
        
        private string fiscalCodeField;
        
        private double quotaField;
        
        private System.DateTime initialDateField;
        
        private System.DateTime endDateField;
        
        private int yearField;
        
        private int semesterField;
        
        private PeriodType periodTypeField;
        
        private string levelField;
        
        private string provinceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Struttura {
            get {
                return this.strutturaField;
            }
            set {
                this.strutturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Sector {
            get {
                return this.sectorField;
            }
            set {
                this.sectorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Contract {
            get {
                return this.contractField;
            }
            set {
                this.contractField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EmployCompany {
            get {
                return this.employCompanyField;
            }
            set {
                this.employCompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FiscalCode {
            get {
                return this.fiscalCodeField;
            }
            set {
                this.fiscalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Quota {
            get {
                return this.quotaField;
            }
            set {
                this.quotaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime InitialDate {
            get {
                return this.initialDateField;
            }
            set {
                this.initialDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Semester {
            get {
                return this.semesterField;
            }
            set {
                this.semesterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PeriodType PeriodType {
            get {
                return this.periodTypeField;
            }
            set {
                this.periodTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.fenealgestweb.it")]
    public enum PeriodType {
        
        /// <remarks/>
        Month,
        
        /// <remarks/>
        Semester,
        
        /// <remarks/>
        Interval,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.fenealgestweb.it")]
    public partial class WorkerDTO {
        
        private SubscriptionDTO subscriptionField;
        
        private SubscriptionDTO[] subscriptionsField;
        
        private DocumentDTO[] documentsField;
        
        private int rowNumberField;
        
        private bool isValidField;
        
        private bool existBirthPlaceField;
        
        private bool existLivingPlaceField;
        
        private string nationalityField;
        
        private string lastModiferField;
        
        private string errorsField;
        
        private string nameField;
        
        private string surnameField;
        
        private string fiscalcodeField;
        
        private System.DateTime birthDateField;
        
        private System.DateTime lastUpdateField;
        
        private string birthPlaceField;
        
        private string currentAziendaField;
        
        private string iscrittoAField;
        
        private System.DateTime liberoAlField;
        
        private string livingPlaceField;
        
        private string addressField;
        
        private string capField;
        
        private string phoneField;
        
        /// <remarks/>
        public SubscriptionDTO Subscription {
            get {
                return this.subscriptionField;
            }
            set {
                this.subscriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Subscription")]
        public SubscriptionDTO[] Subscriptions {
            get {
                return this.subscriptionsField;
            }
            set {
                this.subscriptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Document")]
        public DocumentDTO[] Documents {
            get {
                return this.documentsField;
            }
            set {
                this.documentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int RowNumber {
            get {
                return this.rowNumberField;
            }
            set {
                this.rowNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsValid {
            get {
                return this.isValidField;
            }
            set {
                this.isValidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ExistBirthPlace {
            get {
                return this.existBirthPlaceField;
            }
            set {
                this.existBirthPlaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ExistLivingPlace {
            get {
                return this.existLivingPlaceField;
            }
            set {
                this.existLivingPlaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LastModifer {
            get {
                return this.lastModiferField;
            }
            set {
                this.lastModiferField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Fiscalcode {
            get {
                return this.fiscalcodeField;
            }
            set {
                this.fiscalcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime LastUpdate {
            get {
                return this.lastUpdateField;
            }
            set {
                this.lastUpdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BirthPlace {
            get {
                return this.birthPlaceField;
            }
            set {
                this.birthPlaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CurrentAzienda {
            get {
                return this.currentAziendaField;
            }
            set {
                this.currentAziendaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IscrittoA {
            get {
                return this.iscrittoAField;
            }
            set {
                this.iscrittoAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime LiberoAl {
            get {
                return this.liberoAlField;
            }
            set {
                this.liberoAlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LivingPlace {
            get {
                return this.livingPlaceField;
            }
            set {
                this.livingPlaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Cap {
            get {
                return this.capField;
            }
            set {
                this.capField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.fenealgestweb.it")]
    public partial class ExportTrace {
        
        private WorkerDTO[] workersField;
        
        private string erroreField;
        
        private System.DateTime exportDateField;
        
        private string provinceField;
        
        private string exporterMailField;
        
        private int exportNumberField;
        
        private string userNameField;
        
        private string sectorField;
        
        private string exporterNameField;
        
        private string passwordField;
        
        private ExprtType exportTypeField;
        
        private PeriodType periodTypeField;
        
        private System.DateTime initialDateField;
        
        private System.DateTime endDateField;
        
        private int yearField;
        
        private int periodField;
        
        private bool transactedField;
        
        private string strutturaField;
        
        private string areaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Worker")]
        public WorkerDTO[] Workers {
            get {
                return this.workersField;
            }
            set {
                this.workersField = value;
            }
        }
        
        /// <remarks/>
        public string Errore {
            get {
                return this.erroreField;
            }
            set {
                this.erroreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime ExportDate {
            get {
                return this.exportDateField;
            }
            set {
                this.exportDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ExporterMail {
            get {
                return this.exporterMailField;
            }
            set {
                this.exporterMailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ExportNumber {
            get {
                return this.exportNumberField;
            }
            set {
                this.exportNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Sector {
            get {
                return this.sectorField;
            }
            set {
                this.sectorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ExporterName {
            get {
                return this.exporterNameField;
            }
            set {
                this.exporterNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ExprtType ExportType {
            get {
                return this.exportTypeField;
            }
            set {
                this.exportTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PeriodType PeriodType {
            get {
                return this.periodTypeField;
            }
            set {
                this.periodTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime InitialDate {
            get {
                return this.initialDateField;
            }
            set {
                this.initialDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Transacted {
            get {
                return this.transactedField;
            }
            set {
                this.transactedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Struttura {
            get {
                return this.strutturaField;
            }
            set {
                this.strutturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.fenealgestweb.it")]
    public enum ExprtType {
        
        /// <remarks/>
        SimpleExport,
        
        /// <remarks/>
        ProgramExport,
        
        /// <remarks/>
        LiberiExport,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fenealgestweb.it/")]
    public partial class Tesserato {
        
        private int idUtenteField;
        
        private string stampataDaField;
        
        private int indiceField;
        
        private string settoreTesseraField;
        
        private string nomeField;
        
        private string cognomeField;
        
        private string aziendaField;
        
        private string provinciaSindacaleField;
        
        private string aziendaOldField;
        
        private string capField;
        
        private string viaField;
        
        private string comuneField;
        
        private string provinciaField;
        
        /// <remarks/>
        public int IdUtente {
            get {
                return this.idUtenteField;
            }
            set {
                this.idUtenteField = value;
            }
        }
        
        /// <remarks/>
        public string StampataDa {
            get {
                return this.stampataDaField;
            }
            set {
                this.stampataDaField = value;
            }
        }
        
        /// <remarks/>
        public int Indice {
            get {
                return this.indiceField;
            }
            set {
                this.indiceField = value;
            }
        }
        
        /// <remarks/>
        public string SettoreTessera {
            get {
                return this.settoreTesseraField;
            }
            set {
                this.settoreTesseraField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Cognome {
            get {
                return this.cognomeField;
            }
            set {
                this.cognomeField = value;
            }
        }
        
        /// <remarks/>
        public string Azienda {
            get {
                return this.aziendaField;
            }
            set {
                this.aziendaField = value;
            }
        }
        
        /// <remarks/>
        public string ProvinciaSindacale {
            get {
                return this.provinciaSindacaleField;
            }
            set {
                this.provinciaSindacaleField = value;
            }
        }
        
        /// <remarks/>
        public string AziendaOld {
            get {
                return this.aziendaOldField;
            }
            set {
                this.aziendaOldField = value;
            }
        }
        
        /// <remarks/>
        public string Cap {
            get {
                return this.capField;
            }
            set {
                this.capField = value;
            }
        }
        
        /// <remarks/>
        public string Via {
            get {
                return this.viaField;
            }
            set {
                this.viaField = value;
            }
        }
        
        /// <remarks/>
        public string Comune {
            get {
                return this.comuneField;
            }
            set {
                this.comuneField = value;
            }
        }
        
        /// <remarks/>
        public string Provincia {
            get {
                return this.provinciaField;
            }
            set {
                this.provinciaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fenealgestweb.it/")]
    public partial class FiscalData {
        
        private string provinciaField;
        
        private string comuneField;
        
        private string nazioneField;
        
        private System.DateTime dataNascitaField;
        
        private string sessoField;
        
        /// <remarks/>
        public string Provincia {
            get {
                return this.provinciaField;
            }
            set {
                this.provinciaField = value;
            }
        }
        
        /// <remarks/>
        public string Comune {
            get {
                return this.comuneField;
            }
            set {
                this.comuneField = value;
            }
        }
        
        /// <remarks/>
        public string Nazione {
            get {
                return this.nazioneField;
            }
            set {
                this.nazioneField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataNascita {
            get {
                return this.dataNascitaField;
            }
            set {
                this.dataNascitaField = value;
            }
        }
        
        /// <remarks/>
        public string Sesso {
            get {
                return this.sessoField;
            }
            set {
                this.sessoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CalcolaCodiceFiscaleCompletedEventHandler(object sender, CalcolaCodiceFiscaleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalcolaCodiceFiscaleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalcolaCodiceFiscaleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ExportDocumentToExcelCompletedEventHandler(object sender, ExportDocumentToExcelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExportDocumentToExcelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExportDocumentToExcelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CalcolaDatiFiscaliCompletedEventHandler(object sender, CalcolaDatiFiscaliCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalcolaDatiFiscaliCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalcolaDatiFiscaliCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FiscalData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FiscalData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ExportTessereCompletedEventHandler(object sender, ExportTessereCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExportTessereCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExportTessereCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ImportDataCompletedEventHandler(object sender, ImportDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImportDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImportDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591