//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WIN.WEBCONNECTOR.JoinAllServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="JoinAllWebServiceSoap", Namespace="http://www.fenealgestweb.it/")]
    public partial class JoinAllWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ImportIQAOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImportLiberiOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public JoinAllWebService() {
            this.Url = global::WIN.WEBCONNECTOR.Properties.Settings.Default.WIN_WEBCONNECTOR_JoinAllServices_JoinAllWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ImportIQACompletedEventHandler ImportIQACompleted;
        
        /// <remarks/>
        public event ImportLiberiCompletedEventHandler ImportLiberiCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fenealgestweb.it/ImportIQA", RequestNamespace="http://www.fenealgestweb.it/", ResponseNamespace="http://www.fenealgestweb.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ImportIQA(string username, string password, [System.Xml.Serialization.XmlElementAttribute(Namespace="www.fenealgestweb.it")] IQATrace IQATrace) {
            object[] results = this.Invoke("ImportIQA", new object[] {
                        username,
                        password,
                        IQATrace});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ImportIQAAsync(string username, string password, IQATrace IQATrace) {
            this.ImportIQAAsync(username, password, IQATrace, null);
        }
        
        /// <remarks/>
        public void ImportIQAAsync(string username, string password, IQATrace IQATrace, object userState) {
            if ((this.ImportIQAOperationCompleted == null)) {
                this.ImportIQAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportIQAOperationCompleted);
            }
            this.InvokeAsync("ImportIQA", new object[] {
                        username,
                        password,
                        IQATrace}, this.ImportIQAOperationCompleted, userState);
        }
        
        private void OnImportIQAOperationCompleted(object arg) {
            if ((this.ImportIQACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImportIQACompleted(this, new ImportIQACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fenealgestweb.it/ImportLiberi", RequestNamespace="http://www.fenealgestweb.it/", ResponseNamespace="http://www.fenealgestweb.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ImportLiberi(string username, string password, [System.Xml.Serialization.XmlElementAttribute(Namespace="www.fenealgestweb.it")] LiberiTrace LiberiTrace) {
            object[] results = this.Invoke("ImportLiberi", new object[] {
                        username,
                        password,
                        LiberiTrace});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ImportLiberiAsync(string username, string password, LiberiTrace LiberiTrace) {
            this.ImportLiberiAsync(username, password, LiberiTrace, null);
        }
        
        /// <remarks/>
        public void ImportLiberiAsync(string username, string password, LiberiTrace LiberiTrace, object userState) {
            if ((this.ImportLiberiOperationCompleted == null)) {
                this.ImportLiberiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportLiberiOperationCompleted);
            }
            this.InvokeAsync("ImportLiberi", new object[] {
                        username,
                        password,
                        LiberiTrace}, this.ImportLiberiOperationCompleted, userState);
        }
        
        private void OnImportLiberiOperationCompleted(object arg) {
            if ((this.ImportLiberiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImportLiberiCompleted(this, new ImportLiberiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.fenealgestweb.it")]
    public partial class IQATrace {
        
        private IqaTraceDetail[] iqaTraceDetailsField;
        
        private string subjectField;
        
        private string mailtoField;
        
        private string provinciaField;
        
        private int annoField;
        
        private string entityField;
        
        private int periodField;
        
        /// <remarks/>
        public IqaTraceDetail[] IqaTraceDetails {
            get {
                return this.iqaTraceDetailsField;
            }
            set {
                this.iqaTraceDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Mailto {
            get {
                return this.mailtoField;
            }
            set {
                this.mailtoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Provincia {
            get {
                return this.provinciaField;
            }
            set {
                this.provinciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Anno {
            get {
                return this.annoField;
            }
            set {
                this.annoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.fenealgestweb.it")]
    public partial class IqaTraceDetail {
        
        private string cOGNOME_UTENTEField;
        
        private string nOME_UTENTEField;
        
        private string dATA_NASCITA_UTENTEField;
        
        private string fISCALEField;
        
        private string pROVINCIA_NASCITAField;
        
        private string cOMUNE_NASCITAField;
        
        private string pROVINCIAField;
        
        private string cOMUNEField;
        
        private string iNDIRIZZOField;
        
        private string cAPField;
        
        private string tELEFONO1Field;
        
        private string tELEFONO2Field;
        
        private string cODICE_CE_UTENTEField;
        
        private string cODICE_EC_UTENTEField;
        
        private string nOTE_UTENTEField;
        
        private string sETTOREField;
        
        private string eNTEField;
        
        private string aZIENDA_IMPIEGOField;
        
        private string pARTITA_IVAField;
        
        private string pROVINCIA_AZIENDAField;
        
        private string cOMUNE_AZIENDAField;
        
        private string iNDIRIZZO_AZIENDAField;
        
        private string cAP_AZIENDAField;
        
        private string tELEFONO_AZIENDAField;
        
        private string nOTE_AZIENDAField;
        
        private string cODICE_CE_AZIENDAField;
        
        private string cODICE_EC_AZIENDAField;
        
        private string cONTRATTOField;
        
        private string dATA_INIZIOField;
        
        private string dATA_FINEField;
        
        private string qUOTAField;
        
        private string lIVELLOField;
        
        private string nOTEField;
        
        private string oRE_LAVORATEField;
        
        private string oRE_MALATTIA_INFORTUNIOField;
        
        private string nOME_REFERENTEField;
        
        private string cOGNOME_REFERENTEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string COGNOME_UTENTE {
            get {
                return this.cOGNOME_UTENTEField;
            }
            set {
                this.cOGNOME_UTENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NOME_UTENTE {
            get {
                return this.nOME_UTENTEField;
            }
            set {
                this.nOME_UTENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DATA_NASCITA_UTENTE {
            get {
                return this.dATA_NASCITA_UTENTEField;
            }
            set {
                this.dATA_NASCITA_UTENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FISCALE {
            get {
                return this.fISCALEField;
            }
            set {
                this.fISCALEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PROVINCIA_NASCITA {
            get {
                return this.pROVINCIA_NASCITAField;
            }
            set {
                this.pROVINCIA_NASCITAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string COMUNE_NASCITA {
            get {
                return this.cOMUNE_NASCITAField;
            }
            set {
                this.cOMUNE_NASCITAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PROVINCIA {
            get {
                return this.pROVINCIAField;
            }
            set {
                this.pROVINCIAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string COMUNE {
            get {
                return this.cOMUNEField;
            }
            set {
                this.cOMUNEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string INDIRIZZO {
            get {
                return this.iNDIRIZZOField;
            }
            set {
                this.iNDIRIZZOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CAP {
            get {
                return this.cAPField;
            }
            set {
                this.cAPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TELEFONO1 {
            get {
                return this.tELEFONO1Field;
            }
            set {
                this.tELEFONO1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TELEFONO2 {
            get {
                return this.tELEFONO2Field;
            }
            set {
                this.tELEFONO2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CODICE_CE_UTENTE {
            get {
                return this.cODICE_CE_UTENTEField;
            }
            set {
                this.cODICE_CE_UTENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CODICE_EC_UTENTE {
            get {
                return this.cODICE_EC_UTENTEField;
            }
            set {
                this.cODICE_EC_UTENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NOTE_UTENTE {
            get {
                return this.nOTE_UTENTEField;
            }
            set {
                this.nOTE_UTENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SETTORE {
            get {
                return this.sETTOREField;
            }
            set {
                this.sETTOREField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ENTE {
            get {
                return this.eNTEField;
            }
            set {
                this.eNTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AZIENDA_IMPIEGO {
            get {
                return this.aZIENDA_IMPIEGOField;
            }
            set {
                this.aZIENDA_IMPIEGOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PARTITA_IVA {
            get {
                return this.pARTITA_IVAField;
            }
            set {
                this.pARTITA_IVAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PROVINCIA_AZIENDA {
            get {
                return this.pROVINCIA_AZIENDAField;
            }
            set {
                this.pROVINCIA_AZIENDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string COMUNE_AZIENDA {
            get {
                return this.cOMUNE_AZIENDAField;
            }
            set {
                this.cOMUNE_AZIENDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string INDIRIZZO_AZIENDA {
            get {
                return this.iNDIRIZZO_AZIENDAField;
            }
            set {
                this.iNDIRIZZO_AZIENDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CAP_AZIENDA {
            get {
                return this.cAP_AZIENDAField;
            }
            set {
                this.cAP_AZIENDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TELEFONO_AZIENDA {
            get {
                return this.tELEFONO_AZIENDAField;
            }
            set {
                this.tELEFONO_AZIENDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NOTE_AZIENDA {
            get {
                return this.nOTE_AZIENDAField;
            }
            set {
                this.nOTE_AZIENDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CODICE_CE_AZIENDA {
            get {
                return this.cODICE_CE_AZIENDAField;
            }
            set {
                this.cODICE_CE_AZIENDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CODICE_EC_AZIENDA {
            get {
                return this.cODICE_EC_AZIENDAField;
            }
            set {
                this.cODICE_EC_AZIENDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CONTRATTO {
            get {
                return this.cONTRATTOField;
            }
            set {
                this.cONTRATTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DATA_INIZIO {
            get {
                return this.dATA_INIZIOField;
            }
            set {
                this.dATA_INIZIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DATA_FINE {
            get {
                return this.dATA_FINEField;
            }
            set {
                this.dATA_FINEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string QUOTA {
            get {
                return this.qUOTAField;
            }
            set {
                this.qUOTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LIVELLO {
            get {
                return this.lIVELLOField;
            }
            set {
                this.lIVELLOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NOTE {
            get {
                return this.nOTEField;
            }
            set {
                this.nOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ORE_LAVORATE {
            get {
                return this.oRE_LAVORATEField;
            }
            set {
                this.oRE_LAVORATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ORE_MALATTIA_INFORTUNIO {
            get {
                return this.oRE_MALATTIA_INFORTUNIOField;
            }
            set {
                this.oRE_MALATTIA_INFORTUNIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NOME_REFERENTE {
            get {
                return this.nOME_REFERENTEField;
            }
            set {
                this.nOME_REFERENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string COGNOME_REFERENTE {
            get {
                return this.cOGNOME_REFERENTEField;
            }
            set {
                this.cOGNOME_REFERENTEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.fenealgestweb.it")]
    public partial class LiberiTraceDetail {
        
        private string cOGNOME_UTENTEField;
        
        private string nOME_UTENTEField;
        
        private string dATA_NASCITA_UTENTEField;
        
        private string fISCALEField;
        
        private string pROVINCIA_NASCITAField;
        
        private string cOMUNE_NASCITAField;
        
        private string pROVINCIAField;
        
        private string cOMUNEField;
        
        private string iNDIRIZZOField;
        
        private string cAPField;
        
        private string tELEFONO1Field;
        
        private string tELEFONO2Field;
        
        private string cODICE_CE_UTENTEField;
        
        private string cODICE_EC_UTENTEField;
        
        private string nOTE_UTENTEField;
        
        private string eNTEField;
        
        private string aZIENDA_IMPIEGOField;
        
        private string pARTITA_IVAField;
        
        private string pROVINCIA_AZIENDAField;
        
        private string cOMUNE_AZIENDAField;
        
        private string iNDIRIZZO_AZIENDAField;
        
        private string cAP_AZIENDAField;
        
        private string tELEFONO_AZIENDAField;
        
        private string nOTE_AZIENDAField;
        
        private string cODICE_CE_AZIENDAField;
        
        private string cODICE_EC_AZIENDAField;
        
        private string cONTRATTOField;
        
        private string dATAField;
        
        private string lIVELLOField;
        
        private string iSCRITTO_AField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string COGNOME_UTENTE {
            get {
                return this.cOGNOME_UTENTEField;
            }
            set {
                this.cOGNOME_UTENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NOME_UTENTE {
            get {
                return this.nOME_UTENTEField;
            }
            set {
                this.nOME_UTENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DATA_NASCITA_UTENTE {
            get {
                return this.dATA_NASCITA_UTENTEField;
            }
            set {
                this.dATA_NASCITA_UTENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FISCALE {
            get {
                return this.fISCALEField;
            }
            set {
                this.fISCALEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PROVINCIA_NASCITA {
            get {
                return this.pROVINCIA_NASCITAField;
            }
            set {
                this.pROVINCIA_NASCITAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string COMUNE_NASCITA {
            get {
                return this.cOMUNE_NASCITAField;
            }
            set {
                this.cOMUNE_NASCITAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PROVINCIA {
            get {
                return this.pROVINCIAField;
            }
            set {
                this.pROVINCIAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string COMUNE {
            get {
                return this.cOMUNEField;
            }
            set {
                this.cOMUNEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string INDIRIZZO {
            get {
                return this.iNDIRIZZOField;
            }
            set {
                this.iNDIRIZZOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CAP {
            get {
                return this.cAPField;
            }
            set {
                this.cAPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TELEFONO1 {
            get {
                return this.tELEFONO1Field;
            }
            set {
                this.tELEFONO1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TELEFONO2 {
            get {
                return this.tELEFONO2Field;
            }
            set {
                this.tELEFONO2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CODICE_CE_UTENTE {
            get {
                return this.cODICE_CE_UTENTEField;
            }
            set {
                this.cODICE_CE_UTENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CODICE_EC_UTENTE {
            get {
                return this.cODICE_EC_UTENTEField;
            }
            set {
                this.cODICE_EC_UTENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NOTE_UTENTE {
            get {
                return this.nOTE_UTENTEField;
            }
            set {
                this.nOTE_UTENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ENTE {
            get {
                return this.eNTEField;
            }
            set {
                this.eNTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AZIENDA_IMPIEGO {
            get {
                return this.aZIENDA_IMPIEGOField;
            }
            set {
                this.aZIENDA_IMPIEGOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PARTITA_IVA {
            get {
                return this.pARTITA_IVAField;
            }
            set {
                this.pARTITA_IVAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PROVINCIA_AZIENDA {
            get {
                return this.pROVINCIA_AZIENDAField;
            }
            set {
                this.pROVINCIA_AZIENDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string COMUNE_AZIENDA {
            get {
                return this.cOMUNE_AZIENDAField;
            }
            set {
                this.cOMUNE_AZIENDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string INDIRIZZO_AZIENDA {
            get {
                return this.iNDIRIZZO_AZIENDAField;
            }
            set {
                this.iNDIRIZZO_AZIENDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CAP_AZIENDA {
            get {
                return this.cAP_AZIENDAField;
            }
            set {
                this.cAP_AZIENDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TELEFONO_AZIENDA {
            get {
                return this.tELEFONO_AZIENDAField;
            }
            set {
                this.tELEFONO_AZIENDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NOTE_AZIENDA {
            get {
                return this.nOTE_AZIENDAField;
            }
            set {
                this.nOTE_AZIENDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CODICE_CE_AZIENDA {
            get {
                return this.cODICE_CE_AZIENDAField;
            }
            set {
                this.cODICE_CE_AZIENDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CODICE_EC_AZIENDA {
            get {
                return this.cODICE_EC_AZIENDAField;
            }
            set {
                this.cODICE_EC_AZIENDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CONTRATTO {
            get {
                return this.cONTRATTOField;
            }
            set {
                this.cONTRATTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DATA {
            get {
                return this.dATAField;
            }
            set {
                this.dATAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LIVELLO {
            get {
                return this.lIVELLOField;
            }
            set {
                this.lIVELLOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ISCRITTO_A {
            get {
                return this.iSCRITTO_AField;
            }
            set {
                this.iSCRITTO_AField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="www.fenealgestweb.it")]
    public partial class LiberiTrace {
        
        private LiberiTraceDetail[] liberiTraceDetailsField;
        
        private string provinciaField;
        
        private string subjectField;
        
        private string mailtoField;
        
        /// <remarks/>
        public LiberiTraceDetail[] LiberiTraceDetails {
            get {
                return this.liberiTraceDetailsField;
            }
            set {
                this.liberiTraceDetailsField = value;
            }
        }
        
        /// <remarks/>
        public string Provincia {
            get {
                return this.provinciaField;
            }
            set {
                this.provinciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Mailto {
            get {
                return this.mailtoField;
            }
            set {
                this.mailtoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ImportIQACompletedEventHandler(object sender, ImportIQACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImportIQACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImportIQACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ImportLiberiCompletedEventHandler(object sender, ImportLiberiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImportLiberiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImportLiberiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591