//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.34209
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace ConsoleApplication1.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SharetopIntegrationSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractPersistenceObject))]
    public partial class SharetopIntegration : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private Credenziali credenzialiValueField;
        
        private System.Threading.SendOrPostCallback SaveCongressoRegionaleOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveCongressoTerritorialeOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveStrutturaOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveRappresentantiOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveRappresentanzeOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindOrganizzativeDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SharetopIntegration() {
            this.Url = global::ConsoleApplication1.Properties.Settings.Default.ConsoleApplication1_localhost_SharetopIntegration;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public Credenziali CredenzialiValue {
            get {
                return this.credenzialiValueField;
            }
            set {
                this.credenzialiValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SaveCongressoRegionaleCompletedEventHandler SaveCongressoRegionaleCompleted;
        
        /// <remarks/>
        public event SaveCongressoTerritorialeCompletedEventHandler SaveCongressoTerritorialeCompleted;
        
        /// <remarks/>
        public event SaveStrutturaCompletedEventHandler SaveStrutturaCompleted;
        
        /// <remarks/>
        public event SaveRappresentantiCompletedEventHandler SaveRappresentantiCompleted;
        
        /// <remarks/>
        public event SaveRappresentanzeCompletedEventHandler SaveRappresentanzeCompleted;
        
        /// <remarks/>
        public event FindOrganizzativeDataCompletedEventHandler FindOrganizzativeDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CredenzialiValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveCongressoRegionale", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SaveCongressoRegionale(CongressoRegionale congresso) {
            object[] results = this.Invoke("SaveCongressoRegionale", new object[] {
                        congresso});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SaveCongressoRegionaleAsync(CongressoRegionale congresso) {
            this.SaveCongressoRegionaleAsync(congresso, null);
        }
        
        /// <remarks/>
        public void SaveCongressoRegionaleAsync(CongressoRegionale congresso, object userState) {
            if ((this.SaveCongressoRegionaleOperationCompleted == null)) {
                this.SaveCongressoRegionaleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveCongressoRegionaleOperationCompleted);
            }
            this.InvokeAsync("SaveCongressoRegionale", new object[] {
                        congresso}, this.SaveCongressoRegionaleOperationCompleted, userState);
        }
        
        private void OnSaveCongressoRegionaleOperationCompleted(object arg) {
            if ((this.SaveCongressoRegionaleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveCongressoRegionaleCompleted(this, new SaveCongressoRegionaleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CredenzialiValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveCongressoTerritoriale", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SaveCongressoTerritoriale(CongressoTerritoriale congresso) {
            object[] results = this.Invoke("SaveCongressoTerritoriale", new object[] {
                        congresso});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SaveCongressoTerritorialeAsync(CongressoTerritoriale congresso) {
            this.SaveCongressoTerritorialeAsync(congresso, null);
        }
        
        /// <remarks/>
        public void SaveCongressoTerritorialeAsync(CongressoTerritoriale congresso, object userState) {
            if ((this.SaveCongressoTerritorialeOperationCompleted == null)) {
                this.SaveCongressoTerritorialeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveCongressoTerritorialeOperationCompleted);
            }
            this.InvokeAsync("SaveCongressoTerritoriale", new object[] {
                        congresso}, this.SaveCongressoTerritorialeOperationCompleted, userState);
        }
        
        private void OnSaveCongressoTerritorialeOperationCompleted(object arg) {
            if ((this.SaveCongressoTerritorialeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveCongressoTerritorialeCompleted(this, new SaveCongressoTerritorialeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CredenzialiValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveStruttura", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SaveStruttura(Struttura struttura) {
            object[] results = this.Invoke("SaveStruttura", new object[] {
                        struttura});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SaveStrutturaAsync(Struttura struttura) {
            this.SaveStrutturaAsync(struttura, null);
        }
        
        /// <remarks/>
        public void SaveStrutturaAsync(Struttura struttura, object userState) {
            if ((this.SaveStrutturaOperationCompleted == null)) {
                this.SaveStrutturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveStrutturaOperationCompleted);
            }
            this.InvokeAsync("SaveStruttura", new object[] {
                        struttura}, this.SaveStrutturaOperationCompleted, userState);
        }
        
        private void OnSaveStrutturaOperationCompleted(object arg) {
            if ((this.SaveStrutturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveStrutturaCompleted(this, new SaveStrutturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CredenzialiValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveRappresentanti", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SaveRappresentanti(Rappresentante[] rappresentanti) {
            object[] results = this.Invoke("SaveRappresentanti", new object[] {
                        rappresentanti});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SaveRappresentantiAsync(Rappresentante[] rappresentanti) {
            this.SaveRappresentantiAsync(rappresentanti, null);
        }
        
        /// <remarks/>
        public void SaveRappresentantiAsync(Rappresentante[] rappresentanti, object userState) {
            if ((this.SaveRappresentantiOperationCompleted == null)) {
                this.SaveRappresentantiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveRappresentantiOperationCompleted);
            }
            this.InvokeAsync("SaveRappresentanti", new object[] {
                        rappresentanti}, this.SaveRappresentantiOperationCompleted, userState);
        }
        
        private void OnSaveRappresentantiOperationCompleted(object arg) {
            if ((this.SaveRappresentantiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveRappresentantiCompleted(this, new SaveRappresentantiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CredenzialiValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveRappresentanze", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SaveRappresentanze(Rappresentanza[] rappresentanze) {
            object[] results = this.Invoke("SaveRappresentanze", new object[] {
                        rappresentanze});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SaveRappresentanzeAsync(Rappresentanza[] rappresentanze) {
            this.SaveRappresentanzeAsync(rappresentanze, null);
        }
        
        /// <remarks/>
        public void SaveRappresentanzeAsync(Rappresentanza[] rappresentanze, object userState) {
            if ((this.SaveRappresentanzeOperationCompleted == null)) {
                this.SaveRappresentanzeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveRappresentanzeOperationCompleted);
            }
            this.InvokeAsync("SaveRappresentanze", new object[] {
                        rappresentanze}, this.SaveRappresentanzeOperationCompleted, userState);
        }
        
        private void OnSaveRappresentanzeOperationCompleted(object arg) {
            if ((this.SaveRappresentanzeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveRappresentanzeCompleted(this, new SaveRappresentanzeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CredenzialiValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FindOrganizzativeData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrganizzativeData FindOrganizzativeData(int regionId, int provinceId, int year) {
            object[] results = this.Invoke("FindOrganizzativeData", new object[] {
                        regionId,
                        provinceId,
                        year});
            return ((OrganizzativeData)(results[0]));
        }
        
        /// <remarks/>
        public void FindOrganizzativeDataAsync(int regionId, int provinceId, int year) {
            this.FindOrganizzativeDataAsync(regionId, provinceId, year, null);
        }
        
        /// <remarks/>
        public void FindOrganizzativeDataAsync(int regionId, int provinceId, int year, object userState) {
            if ((this.FindOrganizzativeDataOperationCompleted == null)) {
                this.FindOrganizzativeDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindOrganizzativeDataOperationCompleted);
            }
            this.InvokeAsync("FindOrganizzativeData", new object[] {
                        regionId,
                        provinceId,
                        year}, this.FindOrganizzativeDataOperationCompleted, userState);
        }
        
        private void OnFindOrganizzativeDataOperationCompleted(object arg) {
            if ((this.FindOrganizzativeDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindOrganizzativeDataCompleted(this, new FindOrganizzativeDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class Credenziali : System.Web.Services.Protocols.SoapHeader {
        
        private string userNameField;
        
        private string passwordField;
        
        private string provinceField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrganizzativeData {
        
        private Struttura strutturaField;
        
        private CongressoRegionale congressoRegionaleField;
        
        private CongressoTerritoriale congressoTerritorialeField;
        
        private Rappresentante[] rappresentantiField;
        
        private Rappresentanza[] rappresentanzeField;
        
        private string firstLevelErrorField;
        
        /// <remarks/>
        public Struttura Struttura {
            get {
                return this.strutturaField;
            }
            set {
                this.strutturaField = value;
            }
        }
        
        /// <remarks/>
        public CongressoRegionale CongressoRegionale {
            get {
                return this.congressoRegionaleField;
            }
            set {
                this.congressoRegionaleField = value;
            }
        }
        
        /// <remarks/>
        public CongressoTerritoriale CongressoTerritoriale {
            get {
                return this.congressoTerritorialeField;
            }
            set {
                this.congressoTerritorialeField = value;
            }
        }
        
        /// <remarks/>
        public Rappresentante[] Rappresentanti {
            get {
                return this.rappresentantiField;
            }
            set {
                this.rappresentantiField = value;
            }
        }
        
        /// <remarks/>
        public Rappresentanza[] Rappresentanze {
            get {
                return this.rappresentanzeField;
            }
            set {
                this.rappresentanzeField = value;
            }
        }
        
        /// <remarks/>
        public string FirstLevelError {
            get {
                return this.firstLevelErrorField;
            }
            set {
                this.firstLevelErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Struttura : SharetopIntegragrationSuperClass {
        
        private string indirizzoField;
        
        private string recapitiTelefoniciField;
        
        private string mailField;
        
        private string sitoInternetField;
        
        private CoordinataBancaria[] coordinateBancarieField;
        
        /// <remarks/>
        public string Indirizzo {
            get {
                return this.indirizzoField;
            }
            set {
                this.indirizzoField = value;
            }
        }
        
        /// <remarks/>
        public string RecapitiTelefonici {
            get {
                return this.recapitiTelefoniciField;
            }
            set {
                this.recapitiTelefoniciField = value;
            }
        }
        
        /// <remarks/>
        public string Mail {
            get {
                return this.mailField;
            }
            set {
                this.mailField = value;
            }
        }
        
        /// <remarks/>
        public string SitoInternet {
            get {
                return this.sitoInternetField;
            }
            set {
                this.sitoInternetField = value;
            }
        }
        
        /// <remarks/>
        public CoordinataBancaria[] CoordinateBancarie {
            get {
                return this.coordinateBancarieField;
            }
            set {
                this.coordinateBancarieField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CoordinataBancaria : AbstractPersistenceObject {
        
        private string ibanField;
        
        private string bancaField;
        
        private string indirizzoField;
        
        private string numAgenziaField;
        
        private int id_StrutturaField;
        
        /// <remarks/>
        public string Iban {
            get {
                return this.ibanField;
            }
            set {
                this.ibanField = value;
            }
        }
        
        /// <remarks/>
        public string Banca {
            get {
                return this.bancaField;
            }
            set {
                this.bancaField = value;
            }
        }
        
        /// <remarks/>
        public string Indirizzo {
            get {
                return this.indirizzoField;
            }
            set {
                this.indirizzoField = value;
            }
        }
        
        /// <remarks/>
        public string NumAgenzia {
            get {
                return this.numAgenziaField;
            }
            set {
                this.numAgenziaField = value;
            }
        }
        
        /// <remarks/>
        public int Id_Struttura {
            get {
                return this.id_StrutturaField;
            }
            set {
                this.id_StrutturaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SharetopIntegragrationSuperClass))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Rappresentanza))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Rappresentante))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Struttura))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CongressoTerritoriale))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CongressoRegionale))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CoordinataBancaria))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Provincia))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Regione))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AbstractPersistenceObject {
        
        private bool nonCancellabileField;
        
        private System.DateTime dataCreazioneField;
        
        private System.DateTime dataModificaField;
        
        private string creatoDaField;
        
        private string modificatoDaField;
        
        private int versioneField;
        
        private int idField;
        
        private Key keyField;
        
        private object[] validationErrorsField;
        
        private string descrizioneField;
        
        /// <remarks/>
        public bool NonCancellabile {
            get {
                return this.nonCancellabileField;
            }
            set {
                this.nonCancellabileField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataCreazione {
            get {
                return this.dataCreazioneField;
            }
            set {
                this.dataCreazioneField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataModifica {
            get {
                return this.dataModificaField;
            }
            set {
                this.dataModificaField = value;
            }
        }
        
        /// <remarks/>
        public string CreatoDa {
            get {
                return this.creatoDaField;
            }
            set {
                this.creatoDaField = value;
            }
        }
        
        /// <remarks/>
        public string ModificatoDa {
            get {
                return this.modificatoDaField;
            }
            set {
                this.modificatoDaField = value;
            }
        }
        
        /// <remarks/>
        public int Versione {
            get {
                return this.versioneField;
            }
            set {
                this.versioneField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public Key Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public object[] ValidationErrors {
            get {
                return this.validationErrorsField;
            }
            set {
                this.validationErrorsField = value;
            }
        }
        
        /// <remarks/>
        public string Descrizione {
            get {
                return this.descrizioneField;
            }
            set {
                this.descrizioneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Key {
        
        private int idField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Rappresentanza))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Rappresentante))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Struttura))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CongressoTerritoriale))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CongressoRegionale))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SharetopIntegragrationSuperClass : AbstractPersistenceObject {
        
        private SharetopBaseData baseDataField;
        
        /// <remarks/>
        public SharetopBaseData BaseData {
            get {
                return this.baseDataField;
            }
            set {
                this.baseDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SharetopBaseData {
        
        private int surveyIdField;
        
        private Regione regioneField;
        
        private Provincia provinciaField;
        
        private int annoField;
        
        private OperationResult operationResultField;
        
        /// <remarks/>
        public int SurveyId {
            get {
                return this.surveyIdField;
            }
            set {
                this.surveyIdField = value;
            }
        }
        
        /// <remarks/>
        public Regione Regione {
            get {
                return this.regioneField;
            }
            set {
                this.regioneField = value;
            }
        }
        
        /// <remarks/>
        public Provincia Provincia {
            get {
                return this.provinciaField;
            }
            set {
                this.provinciaField = value;
            }
        }
        
        /// <remarks/>
        public int Anno {
            get {
                return this.annoField;
            }
            set {
                this.annoField = value;
            }
        }
        
        /// <remarks/>
        public OperationResult OperationResult {
            get {
                return this.operationResultField;
            }
            set {
                this.operationResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Regione : AbstractPersistenceObject {
        
        private object[] listaProvincieField;
        
        private object[] listaComuniField;
        
        /// <remarks/>
        public object[] ListaProvincie {
            get {
                return this.listaProvincieField;
            }
            set {
                this.listaProvincieField = value;
            }
        }
        
        /// <remarks/>
        public object[] ListaComuni {
            get {
                return this.listaComuniField;
            }
            set {
                this.listaComuniField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Provincia : AbstractPersistenceObject {
        
        private object[] listaComuniField;
        
        /// <remarks/>
        public object[] ListaComuni {
            get {
                return this.listaComuniField;
            }
            set {
                this.listaComuniField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OperationResult {
        
        private string errorField;
        
        /// <remarks/>
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Rappresentanza : SharetopIntegragrationSuperClass {
        
        private string aziendaField;
        
        private string codInpsAziendaField;
        
        private string provinciaAziendaField;
        
        private string comuneAziendaField;
        
        private string contrattoField;
        
        private int numDipendentiField;
        
        private int numIscrittiFenealField;
        
        private int votiListaFenealField;
        
        private string tipoNominaField;
        
        private System.DateTime dataElezioneField;
        
        private int numRappresentantiFenealField;
        
        private string urlVerbaleField;
        
        /// <remarks/>
        public string Azienda {
            get {
                return this.aziendaField;
            }
            set {
                this.aziendaField = value;
            }
        }
        
        /// <remarks/>
        public string CodInpsAzienda {
            get {
                return this.codInpsAziendaField;
            }
            set {
                this.codInpsAziendaField = value;
            }
        }
        
        /// <remarks/>
        public string ProvinciaAzienda {
            get {
                return this.provinciaAziendaField;
            }
            set {
                this.provinciaAziendaField = value;
            }
        }
        
        /// <remarks/>
        public string ComuneAzienda {
            get {
                return this.comuneAziendaField;
            }
            set {
                this.comuneAziendaField = value;
            }
        }
        
        /// <remarks/>
        public string Contratto {
            get {
                return this.contrattoField;
            }
            set {
                this.contrattoField = value;
            }
        }
        
        /// <remarks/>
        public int NumDipendenti {
            get {
                return this.numDipendentiField;
            }
            set {
                this.numDipendentiField = value;
            }
        }
        
        /// <remarks/>
        public int NumIscrittiFeneal {
            get {
                return this.numIscrittiFenealField;
            }
            set {
                this.numIscrittiFenealField = value;
            }
        }
        
        /// <remarks/>
        public int VotiListaFeneal {
            get {
                return this.votiListaFenealField;
            }
            set {
                this.votiListaFenealField = value;
            }
        }
        
        /// <remarks/>
        public string TipoNomina {
            get {
                return this.tipoNominaField;
            }
            set {
                this.tipoNominaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataElezione {
            get {
                return this.dataElezioneField;
            }
            set {
                this.dataElezioneField = value;
            }
        }
        
        /// <remarks/>
        public int NumRappresentantiFeneal {
            get {
                return this.numRappresentantiFenealField;
            }
            set {
                this.numRappresentantiFenealField = value;
            }
        }
        
        /// <remarks/>
        public string UrlVerbale {
            get {
                return this.urlVerbaleField;
            }
            set {
                this.urlVerbaleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Rappresentante : SharetopIntegragrationSuperClass {
        
        private string cognomeField;
        
        private string nomeField;
        
        private string codiceFiscaleField;
        
        private string telefonoField;
        
        private string mailField;
        
        private string aziendaField;
        
        private string codInpsAziendaField;
        
        private string provinciaAziendaField;
        
        private string comuneAziendaField;
        
        private string contrattoField;
        
        private string tipoField;
        
        /// <remarks/>
        public string Cognome {
            get {
                return this.cognomeField;
            }
            set {
                this.cognomeField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string CodiceFiscale {
            get {
                return this.codiceFiscaleField;
            }
            set {
                this.codiceFiscaleField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        public string Mail {
            get {
                return this.mailField;
            }
            set {
                this.mailField = value;
            }
        }
        
        /// <remarks/>
        public string Azienda {
            get {
                return this.aziendaField;
            }
            set {
                this.aziendaField = value;
            }
        }
        
        /// <remarks/>
        public string CodInpsAzienda {
            get {
                return this.codInpsAziendaField;
            }
            set {
                this.codInpsAziendaField = value;
            }
        }
        
        /// <remarks/>
        public string ProvinciaAzienda {
            get {
                return this.provinciaAziendaField;
            }
            set {
                this.provinciaAziendaField = value;
            }
        }
        
        /// <remarks/>
        public string ComuneAzienda {
            get {
                return this.comuneAziendaField;
            }
            set {
                this.comuneAziendaField = value;
            }
        }
        
        /// <remarks/>
        public string Contratto {
            get {
                return this.contrattoField;
            }
            set {
                this.contrattoField = value;
            }
        }
        
        /// <remarks/>
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CongressoTerritoriale : SharetopIntegragrationSuperClass {
        
        private string segretarioGeneraleField;
        
        private string segretarioOrganizzativoField;
        
        private string membriSegretariaField;
        
        private string tesoriereField;
        
        private string consiglioTerritorialeField;
        
        private string consiglioTerritorialeSupplenteField;
        
        private string assembleaTerritorialeField;
        
        private string assembleaTerritorialeSupplenteField;
        
        private string revisoriDeiContiField;
        
        /// <remarks/>
        public string SegretarioGenerale {
            get {
                return this.segretarioGeneraleField;
            }
            set {
                this.segretarioGeneraleField = value;
            }
        }
        
        /// <remarks/>
        public string SegretarioOrganizzativo {
            get {
                return this.segretarioOrganizzativoField;
            }
            set {
                this.segretarioOrganizzativoField = value;
            }
        }
        
        /// <remarks/>
        public string MembriSegretaria {
            get {
                return this.membriSegretariaField;
            }
            set {
                this.membriSegretariaField = value;
            }
        }
        
        /// <remarks/>
        public string Tesoriere {
            get {
                return this.tesoriereField;
            }
            set {
                this.tesoriereField = value;
            }
        }
        
        /// <remarks/>
        public string ConsiglioTerritoriale {
            get {
                return this.consiglioTerritorialeField;
            }
            set {
                this.consiglioTerritorialeField = value;
            }
        }
        
        /// <remarks/>
        public string ConsiglioTerritorialeSupplente {
            get {
                return this.consiglioTerritorialeSupplenteField;
            }
            set {
                this.consiglioTerritorialeSupplenteField = value;
            }
        }
        
        /// <remarks/>
        public string AssembleaTerritoriale {
            get {
                return this.assembleaTerritorialeField;
            }
            set {
                this.assembleaTerritorialeField = value;
            }
        }
        
        /// <remarks/>
        public string AssembleaTerritorialeSupplente {
            get {
                return this.assembleaTerritorialeSupplenteField;
            }
            set {
                this.assembleaTerritorialeSupplenteField = value;
            }
        }
        
        /// <remarks/>
        public string RevisoriDeiConti {
            get {
                return this.revisoriDeiContiField;
            }
            set {
                this.revisoriDeiContiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CongressoRegionale : SharetopIntegragrationSuperClass {
        
        private string segretarioGeneraleField;
        
        private string segretarioOrganizzativoField;
        
        private string membriSegretariaField;
        
        private string tesoriereField;
        
        private string consiglioTerritorialeField;
        
        private string consiglioTerritorialeSupplenteField;
        
        private string assembleaTerritorialeField;
        
        private string assembleaTerritorialeSupplenteField;
        
        private string revisoriDeiContiField;
        
        private string probiviriField;
        
        /// <remarks/>
        public string SegretarioGenerale {
            get {
                return this.segretarioGeneraleField;
            }
            set {
                this.segretarioGeneraleField = value;
            }
        }
        
        /// <remarks/>
        public string SegretarioOrganizzativo {
            get {
                return this.segretarioOrganizzativoField;
            }
            set {
                this.segretarioOrganizzativoField = value;
            }
        }
        
        /// <remarks/>
        public string MembriSegretaria {
            get {
                return this.membriSegretariaField;
            }
            set {
                this.membriSegretariaField = value;
            }
        }
        
        /// <remarks/>
        public string Tesoriere {
            get {
                return this.tesoriereField;
            }
            set {
                this.tesoriereField = value;
            }
        }
        
        /// <remarks/>
        public string ConsiglioTerritoriale {
            get {
                return this.consiglioTerritorialeField;
            }
            set {
                this.consiglioTerritorialeField = value;
            }
        }
        
        /// <remarks/>
        public string ConsiglioTerritorialeSupplente {
            get {
                return this.consiglioTerritorialeSupplenteField;
            }
            set {
                this.consiglioTerritorialeSupplenteField = value;
            }
        }
        
        /// <remarks/>
        public string AssembleaTerritoriale {
            get {
                return this.assembleaTerritorialeField;
            }
            set {
                this.assembleaTerritorialeField = value;
            }
        }
        
        /// <remarks/>
        public string AssembleaTerritorialeSupplente {
            get {
                return this.assembleaTerritorialeSupplenteField;
            }
            set {
                this.assembleaTerritorialeSupplenteField = value;
            }
        }
        
        /// <remarks/>
        public string RevisoriDeiConti {
            get {
                return this.revisoriDeiContiField;
            }
            set {
                this.revisoriDeiContiField = value;
            }
        }
        
        /// <remarks/>
        public string Probiviri {
            get {
                return this.probiviriField;
            }
            set {
                this.probiviriField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SaveCongressoRegionaleCompletedEventHandler(object sender, SaveCongressoRegionaleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveCongressoRegionaleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveCongressoRegionaleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SaveCongressoTerritorialeCompletedEventHandler(object sender, SaveCongressoTerritorialeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveCongressoTerritorialeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveCongressoTerritorialeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SaveStrutturaCompletedEventHandler(object sender, SaveStrutturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveStrutturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveStrutturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SaveRappresentantiCompletedEventHandler(object sender, SaveRappresentantiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveRappresentantiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveRappresentantiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SaveRappresentanzeCompletedEventHandler(object sender, SaveRappresentanzeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveRappresentanzeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveRappresentanzeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void FindOrganizzativeDataCompletedEventHandler(object sender, FindOrganizzativeDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindOrganizzativeDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindOrganizzativeDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrganizzativeData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrganizzativeData)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591